config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: "homes#top"
  resources :users
  resources :books
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image
  belongs_to :user

 validates :title, presence: true
 validates :body, presence: true, length: {maximum: 200}

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
  @book = Book.new(book_params)
  @book.user = current_user
  if @book.save
    flash[:notice] = "新規投稿successfully"
    redirect_to book_path(@book.id)
  else
    @books = Book.all
    @user = current_user
    render :index
  end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @show = Book.find(params[:id])
    @user = User.find(@show.user.id)

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "投稿更新successfully"
     redirect_to book_path(@book.id)
    else
     render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_info.html.erb
<div>
  <% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>
<div>
  <h1>User info</h1>
  <div class="border-bottom">
    <%= image_tag user.get_profile_image %>
  </div>
  <table width="30%">
  <tr>
    <th>name</th>
    <td><%= user.name %></td>
  </tr>
  <tr align="center">
    <th>introduction</th>
    <td><%= user.introduction  %></td>
  </tr>
  </table>
</div>

<div>
<%= link_to edit_user_path(user.id) do %>
<i class="fas fa-user-cog"></i>
<% end %>
</div>
<div>
  <h1>New book</h1>
  <%= form_with(model: book, local: true) do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %><br>
  <%= f.submit "Create Book", class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
<p>Title</p>
<%= f.text_field :title %>
<P>Opinion</P>
<%= f.text_area :body %><br>
<%= f.submit 'Update Book', class: "btn btn-secondary" %>
<% end %>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<main class="container">
<div class="row">
<div class="col-md-3">
<%= render 'info', book: @book, user: @user %>
</div>
<div class="col-md-8 offset-md-1">
<div class="border-bottom"><h1>Books</h1></div>
<table width="50%">
<tr>
  <th> </th>
  <th>Title</th>
  <th>Opinion</th>
</tr>
<div>
<% @books.each do |book| %>
<div>
<tr align="center">
<td>
<%= link_to user_path(book.user.id) do %>
<%= image_tag book.user.get_profile_image %>
<% end %>
</td>
<td><%= link_to book.title, book_path(book.id) %></td>
<td><%= book.body %></td>
</tr>
<% end %>
</table>
</div>
</div>
</div>
</div>
</main>

app/views/books/show.html.erb
<main class=" container">
<div class="row">
<div class="col-md-3">
<%= render 'info', book: @book, user: @user %>
</div>
<div class="col-md-8 offset-md-1">
<h1>Book detail</h1>
<table width="50%">
<tr align="center">

<td>
  <%= image_tag @show.user.get_profile_image %>
  <%= link_to @show.user.name, user_path(@show.user.id) %>
</td>
<td><%= link_to @show.user.name, user_path(@show.user.id) %></td>
<td><%= link_to @show.title, book_path(@show) %></td>
<td><%= @show.body %></td>

<% if @show.user == current_user %>
<td><%= link_to "Edit", edit_book_path(@show), class: "btn btn-secondary" %></td>
<% end %>
<% if @show.user == current_user %>
<td><%= link_to "Destroy", book_path(@show), method: :delete, class: "btn btn-secondary" %></td>
<% end %>

</tr>
</table>
</div>
</div>
</main>