config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root to: "homes#top"
  resources :users
  resources :books
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/22ce9d1221.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar-dark bg-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-2" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  　　　　　　<span class="navbar-toggler-icon"></span>
　　　　　</button>
　　　　　<div class="navbar-collapse" id="navbarNavDropdown">
 　　　　　　　 <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-link navbar-light">
       <i class="fas fa-home"></i>
        <%= link_to "Home", user_path(current_user.id), class:"text-light" %>
      </li>
      <li class="nav-link text-light">
        <i class="fas fa-users"></i>
        <%= link_to "Users", users_path %>
      </li>
      <li class="nav-link text-light">
        <i class="fas fa-book-open"></i>
        <%= link_to "Books", books_path %>
      </li>
      <li class="nav-link text-light">
        <i class="fas fa-sign-out-alt"></i>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li class="nav-link text-light">
      <% else %>
      <li class="nav-link text-light">
        <i class="fas fa-home"></i>
        <%= link_to "Home", root_path %>
      </li>
      <li class="nav-link text-light">
        <i class="fas fa-link"></i>
        <%= link_to "About", about_path %>
      </li>
      <li class="nav-link text-light">
        <i class="fas fa-user-plus"></i>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li class="nav-link text-light">
        <i class="fas fa-sign-in-alt"></i>
        <%= link_to "Log in", new_user_session_path %>
      </li>
      <% end %>
      </ul>
      </div>
      </div>
      </nav>
    </header>
    <div><%= flash[:notice] %></div>

    <%= yield %>

    <footer class="container">
    <div class="row">
     <div class="mx-auto">
       <p>CopyRight Infratop.inc</p>
     </div>
    </div>
    </footer>
  </body>
</html>